import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author fatmaal-wasmi
 */
public class CourseSchedulerGUI extends javax.swing.JFrame {

    /**
     * Creates new form CourseSchedulerGUI
     */
    private String currentSemester; 
    
    public CourseSchedulerGUI() {
        initComponents();
        rebuildSemesterComboBoxes();
        rebuildSelectCourseComboBox();
        rebuildSelectStudentComboBox();
    }
    
    public void rebuildSemesterComboBoxes() //semestercomboBox top of gui
    {
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        changeSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
        if (semesters.size() > 0)
        {
            DisplaySemesterLabel.setText(semesters.get(0));
            currentSemester = semesters.get(0);
        }
        else
        {
            DisplaySemesterLabel.setText("None, add a semester.");
            currentSemester = "None";
        }
    }
    
    public void rebuildSelectCourseComboBox(){
         ArrayList<String> courses = CourseQueries.getAllCourseCodes(currentSemester);
        SelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
    }
    
    public void rebuildSelectStudentComboBox(){
        ArrayList<StudentEntry> students = StudentQueries.getAllStudents();
        SelectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
         SelectStudentComboBox1.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        
    }
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        CurrentSemesterLabel = new javax.swing.JLabel();
        DisplaySemesterLabel = new javax.swing.JLabel();
        changeSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();
        AdminTab = new javax.swing.JTabbedPane();
        AdminPanel = new javax.swing.JPanel();
        AddSemesterTab = new javax.swing.JTabbedPane();
        AddSemesterPanel = new javax.swing.JPanel();
        SemesterLabel = new javax.swing.JLabel();
        DisplaySemesterTextField2 = new javax.swing.JTextField();
        addSemesterButton = new javax.swing.JButton();
        addSemesterSatusLabel = new javax.swing.JLabel();
        AddStudentPanel = new javax.swing.JPanel();
        StudentIDLabel = new javax.swing.JLabel();
        StudentIDTextField = new javax.swing.JTextField();
        StudentFirstNameLabel = new javax.swing.JLabel();
        StudentFirstNameTextField = new javax.swing.JTextField();
        StudentLastNameLabel = new javax.swing.JLabel();
        StudentLastNameTextField = new javax.swing.JTextField();
        AddStudentButton = new javax.swing.JButton();
        AddStudentResultLabel = new javax.swing.JLabel();
        AddCoursePanel = new javax.swing.JPanel();
        AddCodeLabel = new javax.swing.JLabel();
        CourseDescriptionLabel = new javax.swing.JLabel();
        MaxNumStudentsLabel = new javax.swing.JLabel();
        CourseCodeTextField = new javax.swing.JTextField();
        CourseDescrpitionTextField = new javax.swing.JTextField();
        AddCourseButton = new javax.swing.JButton();
        MaxNumStudentsSpinner = new javax.swing.JSpinner();
        AddCourseResultLabel = new javax.swing.JLabel();
        StudentPanel = new javax.swing.JPanel();
        DisplayScheduleTab = new javax.swing.JTabbedPane();
        ScheduleCoursePanel = new javax.swing.JPanel();
        SelectCourseLabel = new javax.swing.JLabel();
        SelectCourseComboBox = new javax.swing.JComboBox<>();
        ScheduleCourseButton = new javax.swing.JButton();
        SelectStudentLabel = new javax.swing.JLabel();
        SelectStudentComboBox = new javax.swing.JComboBox<>();
        ScheduleCourseLabel = new javax.swing.JLabel();
        DisplayCoursePanel = new javax.swing.JPanel();
        DisplayCourseTabel = new javax.swing.JScrollPane();
        DisplayCourseTable = new javax.swing.JTable();
        DisplayCourseButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        DisplayCourseTabel1 = new javax.swing.JScrollPane();
        DisplayScheduleTable = new javax.swing.JTable();
        DisplayScheduleButton = new javax.swing.JButton();
        SelectStudentLabel1 = new javax.swing.JLabel();
        SelectStudentComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 102, 255));
        Title.setText("Course Scheduler");

        CurrentSemesterLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        CurrentSemesterLabel.setText("Current Semester:");

        DisplaySemesterLabel.setText("none");

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        SemesterLabel.setText("Semester ");

        DisplaySemesterTextField2.setColumns(20);

        addSemesterButton.setText("Submit");
        addSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AddSemesterPanelLayout = new javax.swing.GroupLayout(AddSemesterPanel);
        AddSemesterPanel.setLayout(AddSemesterPanelLayout);
        AddSemesterPanelLayout.setHorizontalGroup(
            AddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSemesterPanelLayout.createSequentialGroup()
                .addGroup(AddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddSemesterPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SemesterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DisplaySemesterTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddSemesterPanelLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(addSemesterButton))
                    .addGroup(AddSemesterPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(addSemesterSatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(490, Short.MAX_VALUE))
        );
        AddSemesterPanelLayout.setVerticalGroup(
            AddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddSemesterPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(AddSemesterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SemesterLabel)
                    .addComponent(DisplaySemesterTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addSemesterButton)
                .addGap(18, 18, 18)
                .addComponent(addSemesterSatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );

        AddSemesterTab.addTab("Add semster", AddSemesterPanel);

        StudentIDLabel.setText("Srudent ID");

        StudentIDTextField.setColumns(10);

        StudentFirstNameLabel.setText("Student First Name");

        StudentFirstNameTextField.setColumns(10);

        StudentLastNameLabel.setText("Student Last Name");

        StudentLastNameTextField.setColumns(10);

        AddStudentButton.setText("Submit");
        AddStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddStudentButtonActionPerformed(evt);
            }
        });

        AddStudentResultLabel.setText("           ");

        javax.swing.GroupLayout AddStudentPanelLayout = new javax.swing.GroupLayout(AddStudentPanel);
        AddStudentPanel.setLayout(AddStudentPanelLayout);
        AddStudentPanelLayout.setHorizontalGroup(
            AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentPanelLayout.createSequentialGroup()
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddStudentPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(AddStudentPanelLayout.createSequentialGroup()
                                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(StudentFirstNameLabel)
                                    .addComponent(StudentIDLabel))
                                .addGap(32, 32, 32)
                                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(StudentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(AddStudentPanelLayout.createSequentialGroup()
                                .addComponent(StudentLastNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(StudentLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(AddStudentPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(AddStudentButton))
                    .addGroup(AddStudentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AddStudentResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(466, Short.MAX_VALUE))
        );
        AddStudentPanelLayout.setVerticalGroup(
            AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddStudentPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentIDLabel)
                    .addComponent(StudentIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentFirstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentFirstNameLabel))
                .addGap(18, 18, 18)
                .addGroup(AddStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentLastNameLabel)
                    .addComponent(StudentLastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(AddStudentResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(AddStudentButton)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        AddSemesterTab.addTab("Add Student", AddStudentPanel);

        AddCodeLabel.setText("Course Code");

        CourseDescriptionLabel.setText("Course Description");

        MaxNumStudentsLabel.setText("Seats");

        CourseCodeTextField.setColumns(10);

        CourseDescrpitionTextField.setColumns(40);

        AddCourseButton.setText("Submit");
        AddCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCourseButtonActionPerformed(evt);
            }
        });

        AddCourseResultLabel.setText("           ");

        javax.swing.GroupLayout AddCoursePanelLayout = new javax.swing.GroupLayout(AddCoursePanel);
        AddCoursePanel.setLayout(AddCoursePanelLayout);
        AddCoursePanelLayout.setHorizontalGroup(
            AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCoursePanelLayout.createSequentialGroup()
                .addGroup(AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddCoursePanelLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(AddCourseResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddCoursePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddCodeLabel)
                            .addComponent(CourseDescriptionLabel))
                        .addGap(79, 79, 79)
                        .addGroup(AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CourseDescrpitionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CourseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(AddCoursePanelLayout.createSequentialGroup()
                        .addComponent(MaxNumStudentsLabel)
                        .addGap(18, 18, 18)
                        .addComponent(MaxNumStudentsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AddCoursePanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(AddCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        AddCoursePanelLayout.setVerticalGroup(
            AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddCoursePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCodeLabel)
                    .addComponent(CourseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseDescriptionLabel)
                    .addComponent(CourseDescrpitionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(AddCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaxNumStudentsLabel)
                    .addComponent(MaxNumStudentsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(AddCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddCourseResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        AddSemesterTab.addTab("Add Course", AddCoursePanel);

        javax.swing.GroupLayout AdminPanelLayout = new javax.swing.GroupLayout(AdminPanel);
        AdminPanel.setLayout(AdminPanelLayout);
        AdminPanelLayout.setHorizontalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddSemesterTab)
                .addContainerGap())
        );
        AdminPanelLayout.setVerticalGroup(
            AdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddSemesterTab)
        );

        AdminTab.addTab("Admin", AdminPanel);

        SelectCourseLabel.setText("Select Course");

        ScheduleCourseButton.setText("Select");
        ScheduleCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleCourseButtonActionPerformed(evt);
            }
        });

        SelectStudentLabel.setText("Select Student");

        javax.swing.GroupLayout ScheduleCoursePanelLayout = new javax.swing.GroupLayout(ScheduleCoursePanel);
        ScheduleCoursePanel.setLayout(ScheduleCoursePanelLayout);
        ScheduleCoursePanelLayout.setHorizontalGroup(
            ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleCoursePanelLayout.createSequentialGroup()
                .addGroup(ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ScheduleCoursePanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ScheduleCoursePanelLayout.createSequentialGroup()
                                .addComponent(SelectCourseLabel)
                                .addGap(54, 54, 54)
                                .addComponent(SelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ScheduleCoursePanelLayout.createSequentialGroup()
                                .addComponent(SelectStudentLabel)
                                .addGap(18, 18, 18)
                                .addComponent(SelectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ScheduleCoursePanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(ScheduleCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ScheduleCoursePanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(ScheduleCourseButton)))
                .addContainerGap(631, Short.MAX_VALUE))
        );
        ScheduleCoursePanelLayout.setVerticalGroup(
            ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ScheduleCoursePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectCourseLabel)
                    .addComponent(SelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(ScheduleCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectStudentLabel)
                    .addComponent(SelectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(ScheduleCourseButton)
                .addGap(35, 35, 35)
                .addComponent(ScheduleCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        DisplayScheduleTab.addTab("Schedule Course", ScheduleCoursePanel);

        DisplayCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Code", "Description", "Seats"
            }
        ));
        DisplayCourseTabel.setViewportView(DisplayCourseTable);
        if (DisplayCourseTable.getColumnModel().getColumnCount() > 0) {
            DisplayCourseTable.getColumnModel().getColumn(1).setResizable(false);
            DisplayCourseTable.getColumnModel().getColumn(2).setResizable(false);
        }

        DisplayCourseButton.setText("Display");
        DisplayCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DisplayCoursePanelLayout = new javax.swing.GroupLayout(DisplayCoursePanel);
        DisplayCoursePanel.setLayout(DisplayCoursePanelLayout);
        DisplayCoursePanelLayout.setHorizontalGroup(
            DisplayCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DisplayCoursePanelLayout.createSequentialGroup()
                .addComponent(DisplayCourseTabel)
                .addContainerGap())
            .addGroup(DisplayCoursePanelLayout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(DisplayCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DisplayCoursePanelLayout.setVerticalGroup(
            DisplayCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayCoursePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayCourseTabel, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(DisplayCourseButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DisplayScheduleTab.addTab("Display Course", DisplayCoursePanel);

        DisplayScheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Course Code", "Status"
            }
        ));
        DisplayCourseTabel1.setViewportView(DisplayScheduleTable);
        if (DisplayScheduleTable.getColumnModel().getColumnCount() > 0) {
            DisplayScheduleTable.getColumnModel().getColumn(0).setMinWidth(10);
        }

        DisplayScheduleButton.setText("Display");
        DisplayScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayScheduleButtonActionPerformed(evt);
            }
        });

        SelectStudentLabel1.setText("Select Student");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DisplayCourseTabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(SelectStudentLabel1)
                .addGap(38, 38, 38)
                .addComponent(SelectStudentComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DisplayScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(382, 382, 382))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectStudentLabel1)
                    .addComponent(SelectStudentComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(DisplayCourseTabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DisplayScheduleButton)
                .addContainerGap())
        );

        DisplayScheduleTab.addTab("Display Schedule", jPanel1);

        javax.swing.GroupLayout StudentPanelLayout = new javax.swing.GroupLayout(StudentPanel);
        StudentPanel.setLayout(StudentPanelLayout);
        StudentPanelLayout.setHorizontalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DisplayScheduleTab)
        );
        StudentPanelLayout.setVerticalGroup(
            StudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentPanelLayout.createSequentialGroup()
                .addComponent(DisplayScheduleTab, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        AdminTab.addTab("Student", StudentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CurrentSemesterLabel)
                .addGap(36, 36, 36)
                .addComponent(DisplaySemesterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(changeSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(changeSemesterButton)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(AdminTab)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(Title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CurrentSemesterLabel)
                    .addComponent(DisplaySemesterLabel)
                    .addComponent(changeSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton))
                .addGap(18, 18, 18)
                .addComponent(AdminTab))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterButtonActionPerformed
         String semester = DisplaySemesterTextField2.getText();
        SemesterQueries.addSemester(semester);
        addSemesterSatusLabel.setText("Semester " + semester + " has been added.");
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_addSemesterButtonActionPerformed

    private void AddCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCourseButtonActionPerformed
        String CourseCode = CourseCodeTextField.getText();
        String CourseDescription = CourseDescrpitionTextField.getText();
        int seats =(int)MaxNumStudentsSpinner.getValue();
        CourseEntry course = new CourseEntry(currentSemester, CourseCode, CourseDescription, seats);
        CourseQueries.addCourse(course);
        AddCourseResultLabel.setText(CourseCode + " has been added. ");
        rebuildSelectCourseComboBox();
    }//GEN-LAST:event_AddCourseButtonActionPerformed

    private void ScheduleCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleCourseButtonActionPerformed
        ArrayList<StudentEntry> students = StudentQueries.getAllStudents();
        String StudentID = students.get(SelectStudentComboBox1.getSelectedIndex()).getStudentID();
        ArrayList<ScheduleEntry> schedule = ScheduleQueries.getScheduleByStudent(currentSemester, StudentID);
        
        DefaultTableModel DisplayScheduleTableModel = (DefaultTableModel)DisplayScheduleTable.getModel();
        
        DisplayScheduleTableModel.setNumRows(0);
        Object[] rowData = new Object[2];
        
        for(ScheduleEntry entry:schedule)
        {
            rowData[0] = entry.getCourseCode();
            rowData[1] = entry.getSatus();
            DisplayScheduleTableModel.addRow(rowData);
        }       
        
    }//GEN-LAST:event_ScheduleCourseButtonActionPerformed

    private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterButtonActionPerformed
        String semester = changeSemesterComboBox.getSelectedItem().toString();
        DisplaySemesterLabel.setText(semester);
        currentSemester = semester;
        rebuildSelectCourseComboBox();
    }//GEN-LAST:event_changeSemesterButtonActionPerformed

    private void AddStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddStudentButtonActionPerformed
        String StudentID = StudentIDTextField.getText();
        String studentFirstName = StudentFirstNameTextField.getText();
        String studentLastName = StudentLastNameTextField.getText();
        StudentEntry student = new StudentEntry(StudentID, studentFirstName, studentLastName);
        StudentQueries.addStudent(student);
        AddStudentResultLabel.setText(studentFirstName + " " + studentLastName + " has been added.");
        rebuildSelectStudentComboBox();
    }//GEN-LAST:event_AddStudentButtonActionPerformed

    private void DisplayCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCourseButtonActionPerformed
        ArrayList<CourseEntry> courses = CourseQueries.getAllCourses(currentSemester);
        DefaultTableModel DisplayCourseTableModel = (DefaultTableModel)DisplayCourseTable.getModel();
        
        DisplayCourseTableModel.setNumRows(0);
        Object[] rowData = new Object[3];
        
        for(CourseEntry course:courses)
        {
            rowData[0] = course.getCourseCode();
            rowData[1] = course.getDescription();
            rowData[2] = course.getSeats();
            DisplayCourseTableModel.addRow(rowData);
        }       
    }//GEN-LAST:event_DisplayCourseButtonActionPerformed

    private void DisplayScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayScheduleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayScheduleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CourseSchedulerGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CourseSchedulerGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddCodeLabel;
    private javax.swing.JButton AddCourseButton;
    private javax.swing.JPanel AddCoursePanel;
    private javax.swing.JLabel AddCourseResultLabel;
    private javax.swing.JPanel AddSemesterPanel;
    private javax.swing.JTabbedPane AddSemesterTab;
    private javax.swing.JButton AddStudentButton;
    private javax.swing.JPanel AddStudentPanel;
    private javax.swing.JLabel AddStudentResultLabel;
    private javax.swing.JPanel AdminPanel;
    private javax.swing.JTabbedPane AdminTab;
    private javax.swing.JTextField CourseCodeTextField;
    private javax.swing.JLabel CourseDescriptionLabel;
    private javax.swing.JTextField CourseDescrpitionTextField;
    private javax.swing.JLabel CurrentSemesterLabel;
    private javax.swing.JButton DisplayCourseButton;
    private javax.swing.JPanel DisplayCoursePanel;
    private javax.swing.JScrollPane DisplayCourseTabel;
    private javax.swing.JScrollPane DisplayCourseTabel1;
    private javax.swing.JTable DisplayCourseTable;
    private javax.swing.JButton DisplayScheduleButton;
    private javax.swing.JTabbedPane DisplayScheduleTab;
    private javax.swing.JTable DisplayScheduleTable;
    private javax.swing.JLabel DisplaySemesterLabel;
    private javax.swing.JTextField DisplaySemesterTextField2;
    private javax.swing.JLabel MaxNumStudentsLabel;
    private javax.swing.JSpinner MaxNumStudentsSpinner;
    private javax.swing.JButton ScheduleCourseButton;
    private javax.swing.JLabel ScheduleCourseLabel;
    private javax.swing.JPanel ScheduleCoursePanel;
    private javax.swing.JComboBox<String> SelectCourseComboBox;
    private javax.swing.JLabel SelectCourseLabel;
    private javax.swing.JComboBox<String> SelectStudentComboBox;
    private javax.swing.JComboBox<String> SelectStudentComboBox1;
    private javax.swing.JLabel SelectStudentLabel;
    private javax.swing.JLabel SelectStudentLabel1;
    private javax.swing.JLabel SemesterLabel;
    private javax.swing.JLabel StudentFirstNameLabel;
    private javax.swing.JTextField StudentFirstNameTextField;
    private javax.swing.JLabel StudentIDLabel;
    private javax.swing.JTextField StudentIDTextField;
    private javax.swing.JLabel StudentLastNameLabel;
    private javax.swing.JTextField StudentLastNameTextField;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JLabel Title;
    private javax.swing.JButton addSemesterButton;
    private javax.swing.JLabel addSemesterSatusLabel;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> changeSemesterComboBox;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
